import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italiensk',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Kjapt & enkelt',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Hamburgere',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Tysk',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'Lett & ledig',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Eksotisk',
    color: Colors.green,
  ),
  Category(
    id: 'c7',
    title: 'Frokost',
    color: Colors.lightBlue,
  ),
  Category(
    id: 'c8',
    title: 'Asiatisk',
    color: Colors.lightGreen,
  ),
  Category(
    id: 'c9',
    title: 'Fransk',
    color: Colors.pink,
  ),
  Category(
    id: 'c10',
    title: 'Sommer',
    color: Colors.teal,
  ),
  Category(
    id: 'c11',
    title: 'Lett som en plett',
    color: Colors.blueGrey,
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
      'c2',
    ],
    title: 'Spagetti med Tomatsaus',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg/800px-Spaghetti_Bolognese_mit_Parmesan_oder_Grana_Padano.jpg',
    duration: 20,
    ingredients: [
      '4 Tomater',
      '1 ss Olivenolje',
      '1 Løk',
      '250g Spagetti',
      'Krydder',
      'Ost (valgfritt)'
    ],
    steps: [
      'Skjær tomater og løk i små biter.',
      'Kok opp vann - tilsett salt.',
      'Legg spagettien i det kokende vannet. - La den koke 10-12min.',
      'I mellomtiden, varm opp litt olivenolje og stek den oppkuttede løken.',
      'Etter 2min, tilsett tomatbitene, salt, pepper og dine andre krydder.',
      'Sausen er ferdig omtrent samtidig som spagettien.',
      'Strø litt ost over den ferdige retten om du vil.'
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Toast Hawaii',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg',
    duration: 10,
    ingredients: [
      '1 Skive Hvitt Brød',
      '1 Skive Skinke',
      '1 Skive Ananas',
      '1-2 Skiver med Ost',
      'Smør'
    ],
    steps: [
      'Smør på en brødskive',
      'Legg på skinke, ananas og ost',
      'Bak i ovnen på 200°C i 10min'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c2',
      'c3',
    ],
    title: 'Klassisk Hamburger',
    affordability: Affordability.Pricey,
    complexity: Complexity.Simple,
    imageUrl: 'https://cdn.pixabay.com/photo/2014/10/23/18/05/burger-500054_1280.jpg',
    duration: 45,
    ingredients: ['300g Kjøttdeig', '1 Tomat', '1 Agurk', '1 Løk', 'Ketchup', 'Burger Brød'],
    steps: [
      'Lag runde kaker av kjøttdeigen',
      'Fres i stekepanna ca. 4 minutter på hver side',
      'Stek burgerbrøda i ca. 1 minutt på hver side',
      'Sprut på litt ketchup i brøda',
      'Server burgeren med tomat, agurk, løk og evt. andre ting du måtte få lyst på'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Wienerschnitzel',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Challenging,
    imageUrl: 'https://cdn.pixabay.com/photo/2018/03/31/19/29/schnitzel-3279045_1280.jpg',
    duration: 60,
    ingredients: [
      '8 Skiver Kjøtt fra Kalv',
      '4 Egg',
      '200g Griljemel',
      '100g Hvetemel',
      '0.3dl Smør',
      '100g Vegetabilsk Olje',
      'Salt',
      'Sitron i Skiver'
    ],
    steps: [
      'Bank kjøttet mørt og godt til det er 2-4mm, og salt begge sider.',
      'Rør sammen egg på et fat.',
      'Dypp kjøttet først i litt mel, deretter i egg og dekk med griljemel.',
      'Varm smøret og oljen i en stor stekepanne til det blir veldig varmt. Stek deretter scnitzlene til de er gylden brune på begge sider.',
      'Beveg litt på pannen innimellom slik at schnitzlene blir dekket av fett og andre godsaker og at griljemelet blir godt dekket',
      'Tørk på litt kjøkkenpapir.',
      'Server med litt persille og sitronskiver. Persillen kan freses litt i stekepanna etter kjøttet er stekt.'
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2'
          'c5',
      'c10',
    ],
    title: 'Salat med Røkelaks',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl: 'https://cdn.pixabay.com/photo/2016/10/25/13/29/smoked-salmon-salad-1768890_1280.jpg',
    duration: 15,
    ingredients: [
      'Ruccola',
      'Lammesalat',
      'Persille',
      'Fennikel',
      '200g Røkelaks',
      'Sennep',
      'Balsamico Eddik',
      'Oliven Olje',
      'Salt og Pepper'
    ],
    steps: [
      'Vask og skjær salat og urter.',
      'Legg i en salatbolle',
      'Skjær laksen i terninger',
      'Lag dressing av sennep, eddik og olivenolje.',
      'Tilsett laks og dressing i salatblandingen.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c10',
    ],
    title: 'Deilig Appelsin Mousse',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/05/01/05/18/pastry-2274750_1280.jpg',
    duration: 240,
    ingredients: [
      '4 Ark med Gelatin',
      '150ml Appelsinjus',
      '80g Sukker',
      '300g Joghurt',
      '200g Krem',
      'Appelsinskall',
    ],
    steps: [
      'Løs opp gelatin i en gryte.',
      'Tilsett appelsinjus og sukker.',
      'Fjern gryten fra stekeplaten.',
      'Tilsett 2 spiseskjeer joghurt.',
      'Rør sammen gelatin og resten av joghurten.',
      'Kjøl blandingen i et kjøleskap.',
      'Pisk krem og legg under massen i kjøleskapet.',
      'Kjøl videre i 4 timer.',
      'Server med litt topping av høvlet appelsinskall',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c7',
    ],
    title: 'Pannekaker',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://cdn.pixabay.com/photo/2018/07/10/21/23/pancake-3529653_1280.jpg',
    duration: 20,
    ingredients: [
      '1 1/2 Kopp Hvetemel',
      '3 1/2 ts Bakepulver',
      '1 ts Salt',
      '1 ss Sukker',
      '1 1/4 Kopper Melk',
      '1 Egg',
      '3 ss smeltet Smør',
    ],
    steps: [
      'Bland sammen mel, bakepulver, salt og sukker i en stor bolle.',
      'Lag et hulrom i midten og ha i melk, egg og smeltet smør. Bland sammen til en jevn blanding.',
      'Varm opp litt olje i en stekepanne.',
      'Stek pannekakene på begge sider i den varme stekepanna.'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: 'Kremet Indisk Karri Kylling',
    affordability: Affordability.Pricey,
    complexity: Complexity.Challenging,
    imageUrl: 'https://cdn.pixabay.com/photo/2018/06/18/16/05/indian-food-3482749_1280.jpg',
    duration: 35,
    ingredients: [
      '4 Kyllingbryst',
      '1 Løk',
      '2 fedd Hvitløk',
      '1 Bit Ingefær',
      '4 ss Mandler',
      '1 ts cayennepepper',
      '500ml Kokosmelk',
    ],
    steps: [
      'Skjær opp kyllingbryst i passende biter.',
      'Finhakk og mos løk, hvitløk og ingefær til en pasta og smør på kyllingen.',
      'Stek og tilsett krydder mens du rører.',
      'Tilsett 250ml vann og kok i 10 minutt.',
      'Tilsett kokosmelk',
      'Server med ris'
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: 'Sjokolade Suffle',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl: 'https://cdn.pixabay.com/photo/2014/08/07/21/07/souffle-412785_1280.jpg',
    duration: 45,
    ingredients: [
      '1 ts smeltet Smør',
      '2 ss Sukker',
      '60 gram 70% mørk Sjokolade delt opp i biter.',
      '1 ss Smør',
      '1 ss Hvetemel',
      '4 1/3 ss kald Melk',
      '1 Klype Salt',
      '1 Klype Cayennepepper',
      '1 Stor Eggeplomme',
      '2 Store Eggehviter',
      '1 Klype Bakepulver',
      '1 ss sukker',
    ],
    steps: [
      'Forvarm ovnen til 190°C. ',
      'Pensle 2 ark med bakepapir med smeltet smør.',
      'Dryss på 1ss sukker. Dekk hele flatene.',
      'Plasser sjokoladen i en miksebolle av metall.',
      'Plasser bollen i en gryte/dyp stekepanne på stekeplaten fylt med ca. 3 kopper varmt vann. Lav varme på stekeplaten.',
      'Smelt 1 ss smør i en stekepanne på middels varme. Strø over mel. Bland sammen til melet er godt sammenblandet med smøret og blandingen tykner.',
      'Bland sammen med kald melk til det blir jevnt og tykt. Bland inn i bollen med smeltet sjokolade.',
      'Tilsett salt og cayennepepper. Bland sammen godt. Tilsett deretter eggeplomme og bland sammen.',
      'Fortsett og varm opp, men ikke kok. Hold det varmt mens du pisker inn eggehviter.',
      'Pisk sammen 2 eggehviter med bakepulver i en miksebolle. Pisk til det er tjukt.',
      'Tilsett 1/3 av sukkeret og pisk inn. Pisk inn litt mer sukker etter ca 15 sekunder.',
      'Pisk inn resten av sukkeret og fortsett med piskingen til blandingen er tjukt skum.',
      'Tilsett halvparten av eggehviteblandingen i sjokoladeblandingen.',
      'Bland sammen til det er en jevn blanding.',
      'Tilsett resten av eggehviteblandingen. Fold forsiktig inn.',
      'Slutt å bland når eggehvite blandingen forsvinner. Del blandingen på de 2 bakepapir arkene.',
      'Bak i stekeovnen i 12-15 minutter.',
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c2',
      'c5',
      'c10',
    ],
    title: 'Asparges Salat med Cherrytomater',
    affordability: Affordability.Luxurious,
    complexity: Complexity.Simple,
    imageUrl: 'https://cdn.pixabay.com/photo/2018/04/09/18/26/asparagus-3304997_1280.jpg',
    duration: 30,
    ingredients: [
      'Hvit og Grønn Asparges',
      '30g Pinjekjerner',
      '300g Cherrytomater',
      'Salat',
      'Salt, Pepper og Olivenolje'
    ],
    steps: [
      'Vask, skrell og skjær opp asparges.',
      'Kok i salt vann.',
      'Dryss salt og pepper på aspargesen.',
      'Stek pinjekjernene.',
      'Skjær tomatene i halvdeler.',
      'Miks med asparges salat og dressing.',
      'Server med baguette.'
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm11',
    categories: [
      'c11',
      'c7',
    ],
    title: 'Runar\'s Pannekaker',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl: 'https://cdn.pixabay.com/photo/2017/01/30/13/53/pancakes-2020867_640.jpg',
    duration: 40,
    ingredients: [
      '7 dl Hvetemel',
      '1.4l lettmelk',
      '1/2 ts Salt',
      '5-6 Egg',
    ],
    steps: [
      'Bland ingrediensene i en bolle',
      'La stå 15min',
      'Stek pannekakene.',
      'For å få litt fortgang, stek på 2 stekepanner.',
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
  ),
];
